services:
  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    image: postgres:13
    ports:
      - 5433:5432
  web:
    depends_on:
      - db
    image: odoo:11.0
    ports:
      - 8069:8069
      - 8072:8072
    volumes:
      - ./:/mnt/extra-addons
version: '3.1'
